# Generated by Django 3.0.5 on 2020-05-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desti',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
